# router_url = "https://api.infrax.network"
router_url = "http://0.0.0.0:8420"

[host]
external_port = 8069
local_ip = "0.0.0.0"
internal_port = 8069
local_only = false
app_dir = "./installed"

[compute_node]
eth_address = "0xc0ffee254729296a45a3885639AC7E10F9d54979"
cpu = "Intel Core i7-10700K"
gpu = "gtx_1080ti"
# ram 32GB in bytes
ram = "32GB"
vram = "8GB"

# Available floating point formats on GPU. Use true for supported types, false otherwise.
[float_types]
FP80=true
FP64=true
FP32=false
FP16=false
FP8=false
FP4=false
BF16=false
TF32=false
NF4=false
